version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      weekly-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directories:
      - "/functions/packages/site/*"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      shared-function-dependencies:
        group-by: "dependency-name"
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      weekly-actions:
        patterns:
          - "*"
