name: Verify
on: pull_request

jobs:
  verify:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.2
      - name: Install dependencies
        run: |
          gem install bundler --version=2.6.5
          bundle install

      - name: Run Standard
        run: bundle exec standardrb
      - name: Run Bundler Audit
        run: bundle exec bundler-audit --update

